### ISSUE TITLE
Missing platforms/qwindows.dll

### ISSUE THREAD

**Issue by Traace** [ExtraordinaryBen/DuinoBoX#2]
Hi Ben,

your GUI release didn't work for me. I got a error, related that QT coudn't find the proper platform files.

To fix it I grab the source code, compiled it with MinGW-32bit and QT Creator, then drop'd the compatible .dlls from qt's mingw-32bit into the application folder. I assume your system has QT installed with a PATH set for platform runtime files. Therefore you couldn't even notice. :)

Structure should be:
- /DuinoBoX.exe
- /*all_other*.dlls        (like QT5Core.dll etc.)
- /platforms/qwindows.dll      (for release build)

What helped me to track the issue: PATH-> "set QT_DEBUG_PLUGINS=1" + Application: DebugView.

Works fine now ✔️  (I guess)
Thanks again.

I try porting it to C# .net 4.0 soon 👍

**Comment by ExtraordinaryBen** [comment]
Hi @Traace, thank you for reporting this! Guess I'm still learning how to package Qt apps for Windows...

Somehow I didn't notice that the CLI tool `windeployqt` exists: https://doc.qt.io/qt-5/windows-deployment.html

I've re-uploaded the zip, which now includes the missing /platforms/qwindows.dll file. 

Good luck on your C# port! (I had originally thought of writing this in Python, but wasn't sure which would be harder to deploy cross-platform wise.)

**Comment by Traace** [comment]
Every programming language has its pros and cons. But at the end its important that its working. So python is great, too. And I'm sure its more suitable for cross-platform. You did a good pick 👍 

I'm just more familiar with C# :) | A few years before it was pretty hard to get a .net application running on POSIX. These days all whats needed is the `mono` package and only sometimes few little code changes, even windows forms are supported. MS also open-sourced .net framework core components.

BTW: The reader application build from sources runs fine. I was able to readout a 1.6b console. EEPROM.bin is 100% valid. Rebuilding of a HDD was possible. Well done, thanks.


May we can implement a way of decrypting the HDD key. Would it gives us the HDD password? It should be encrypted in `RC4`
Start `0x1C`
End: `0x2B`
More to read: https://xboxdevwiki.net/EEPROM
Decrypting keys: https://xboxdevwiki.net/Kernel/XboxEEPROMKey

**Comment by ExtraordinaryBen** [comment]
Sorry for the delayed response.

Yeah eventually I'd like to decrypt the HDD key. While I could use the Chihiro EEPROM key, I'd rather not use it due to it technically being Microsoft's Intellectual Property. 
There is another method to decrypt without the Chihiro key. The Xbox-Linux project team documented it: http://xbox-linux.sourceforge.net/down/The%20Middle%20Message-1a.pdf

They also have source code that implements this process, but it's written in Visual C++. (I just haven't gotten around to porting it or implementing my own method.)

But this is already getting off topic from the original issue/bug. A new issue can be created to deal with this.

**Comment by debrasteed** [comment]
Ahh! This is a common file that helps games and program to run smoothly, it is a C++ development framework. This is a common error and it has a number of reasons as to why this error pop-ups. Well, it could be due to a problem with hardware/registry as it is incompatible or the error could be as the file infected by Malware or Virus. You first need to recognize the source of error and then you can try my way that is reinstall the [qwindows.dll file](https://coding.fm/qwindows.dll/) at specific path or location.

**Comment by Traace** [comment]
Strange AI these days, trying to act like humans...
